### ISSUE TITLE
大佬，我来催下进度(⊙o⊙)…

### ISSUE THREAD

**Issue by IainZhuo** [haiweilian/vivy-nest-admin#1]
大佬你好，找了好久，找到你这个nestjs带生成器的项目。项目进入稳定阶段没？能否用于生产？看您的文档基本没写，什么时候方便补一下文档呀。小弟不太会nest，没文档可能对我来说使用起来会有点难度。

**Comment by haiweilian** [comment]
文档本地写的差不多了，晚上提交一版优化后的。想参与了可以一起搞。

**Comment by haiweilian** [comment]
最新的代码已经更上去了。

1. 对于我准备写的功能还没有写完。
2. 项目的架构是照顾了分布式微服务项目，所以稍微复杂抽象点。
3. 如果只是要代码生成部分，这是个独立的模块可以参考下自己实现也行。

**Comment by Mahoo12138** [comment]
期待定时任务部分内容，想参考下写法的🤤

**Comment by haiweilian** [comment]
> 期待定时任务部分内容，想参考下写法的🤤

ref: #3
